version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      # Host port : image port
      - "6379:6379"
    # REDIS_URI=redis://localhost:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    restart: on-failure:10

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "8082:80"
    restart: on-failure:10

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    ports:
      - "8083:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    # mongo-express tries to connect immediatly, needs
    # restart: always to retry till it successfuly connects
    restart: always

  mysql:
    image: mysql
    restart: on-failure:10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb

  adminer:
    # Server must be same as image name connecting to
    # For mysql
    # Server: mysql
    # Username: root
    # Password: pass
    # Datanase: mydb
    image: adminer
    restart: always
    ports:
      - "8084:8080"

volumes:
  pgdata:
